language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on:
          branch: master