sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: "jonathan.haeberle@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master